name: Deployment Exercise 1
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

  lint:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test, build]
    steps:
      - name: Deploying code
        run: echo "Deploying..."
